#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,os,time
from collections import Counter
from datetime import datetime
from pathlib import Path
RUN=Path('/home/USER/ttt/runs/formal/kp_factorial_1p7b_v1/run_20260905T235503+0800')
SCREEN=Path('/home/USER/ttt/runs/formal/kp_factorial_screening_1p7b_v1/run_20260905T233846+0800')
RESET=Path('/home/USER/ttt/runs/formal/state_reset_1p7b_v1/run_20260905T180918+0800/manifests/STATE_RESET_167_COHORT.jsonl')
MODEL='ca51ee90d20ee09efbe0b31dd21bf9faa70275508316d1ba7cb1387ee4f0725f';CKPT='f4e264ed6f5671f123d6c8a27c69bce3af5ffcba518c9e298398314c6147d9fd';BENCH='5d16e3a6963d4c21450f0530af743730b91bf7b2442699e288e10754f77ad0c5';RULE='84a3b1e3f6215e6ae94a8b394e92d633440567d4fc19a71375e1cb9be9fabc0a';ELIG='70c08451da1abc11c489eb119c37c9a53b2bad861395f54bdf640d513a51a306';DYN='89e5b7da8b85ce063af15216ef9a16de5c433d4e489a19efaae20ad16099689f'
LAYERS=[0,6,12,18,24]; AL={'OFF':[],'L0':[0],'L6':[6],'L12':[12],'L18':[18],'L24':[24],'ALL':LAYERS}; CELLS={'F00':(0,0),'F10':(1,0),'F01':(0,1),'F11':(1,1)}
def now():return datetime.now().astimezone().isoformat(timespec='seconds')
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def canon(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
def rows(p):return [json.loads(x) for x in Path(p).read_text().splitlines() if x.strip()]
def atomic_text(p,s):
 p=Path(p);p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(f'.{p.name}.{os.getpid()}.{time.time_ns()}.tmp');fd=os.open(t,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o644)
 with os.fdopen(fd,'w') as f:f.write(s);f.flush();os.fsync(f.fileno())
 os.replace(t,p);d=os.open(p.parent,os.O_RDONLY);os.fsync(d);os.close(d)
def atomic(p,o):atomic_text(p,json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+'\n')
def jsonl(p,rs):atomic_text(p,''.join(json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False)+'\n' for x in rs))

def main():
 rule=SCREEN/'manifests/KP_FACTORIAL_RULE_V1.json';elig=SCREEN/'manifests/KP_FACTORIAL_ELIGIBILITY_V1_MANIFEST.json';pool=SCREEN/'pools/KP_FACTORIAL_ELIGIBLE_INDEPENDENT.jsonl';dyn=Path('/home/USER/ttt/runs/formal/dynamic_nonceiling_12task_1p7b_v1/run_20260828T161330+0800/audits/FINAL_DYNAMIC_NONCEILING_12TASK_AUDIT.json')
 checks={'model':sha('/home/USER/ttt/models/qwen3_1p7b_stage2/model.safetensors')==MODEL,'benchmark':sha('/home/USER/ttt/benchmarks/ruler_16k_standard_13task500_v1/benchmark_manifest.json')==BENCH,'rule':sha(rule)==RULE,'eligibility':sha(elig)==ELIG,'dynamic':sha(dyn)==DYN}
 if not all(checks.values()):raise RuntimeError('AUTHORITY_MISMATCH '+repr(checks))
 amendment={'version':'KP_FORMAL_AMENDMENT_V1','frozen_before_formal_outcomes':True,'OUTCOME_SEEN_BEFORE_AMENDMENT':False,'MULTISWITCH_FORMAL_GENERALIZATION':True,'native_schedule':'COMPLETE_ORIGINAL_FROZEN_DYNAMIC_ACTION_SEQUENCE','boundary':'ONE_BASED_START_OF_FINAL_TERMINAL_ACTION_RUN','control_schedule':'OFF_FOR_EVERY_PREBOUNDARY_CHUNK_PLUS_IDENTICAL_COMPLETE_TERMINAL_SUFFIX','P1_used_layer_semantics':'UNION_OF_CANDIDATE_LAYERS_USED_ANYWHERE_IN_COMPLETE_NATIVE_DYNAMIC_SEQUENCE','K1_prefix_positions':'[0,(boundary-1)*1024)','expected_multiswitch_n':71,'created_at':now()}
 atomic(RUN/'preregistration/KP_FORMAL_AMENDMENT_V1.json',amendment)
 atomic_text(RUN/'preregistration/KP_FORMAL_AMENDMENT_V1.md','# K/P Formal Amendment V1\n\nFrozen before formal factorial outcomes. `OUTCOME_SEEN_BEFORE_AMENDMENT=false`; `MULTISWITCH_FORMAL_GENERALIZATION=true`. Native uses the complete frozen Dynamic schedule. The one-based boundary is the start of the final terminal action run. Control replaces every pre-boundary action with OFF and preserves the identical terminal suffix. P1 is the candidate-layer union over the complete Native sequence.\n')
 amend_sha=sha(RUN/'preregistration/KP_FORMAL_AMENDMENT_V1.json')
 ref={x['canonical_sample_id']:x for x in rows(RESET)};eligible=rows(pool);cohort=[]
 for x in eligible:
  sid=x['canonical_sample_id'];seq=x['dynamic_action_sequence'];b=x['boundary']['chunk_index_one_based'];prefix=b-1;suffix=seq[prefix:];switch=sum(seq[i]!=seq[i-1] for i in range(1,len(seq)));used=sorted({l for a in seq for l in AL[a]});r=ref[sid]
  if b!=1+max(i for i in range(1,len(seq)) if seq[i]!=seq[i-1]) or suffix!=[seq[-1]]*len(suffix) or used!=x['native_used_candidate_layers']:raise RuntimeError('AMENDMENT_INVARIANT '+sid)
  cohort.append({'cohort_order':len(cohort)+1,'canonical_sample_id':sid,'task':x['task'],'task_sample_index':x['task_sample_index'],'benchmark_global_index':x['benchmark_global_index'],'benchmark_content_sha256':x['benchmark_content_sha256'],'full_native_dynamic_sequence':seq,'control_prefix_sequence':['OFF']*prefix,'frozen_terminal_suffix':suffix,'boundary':b,'prefix_chunks':prefix,'continuation_chunks':len(suffix),'full_chunk_count':len(seq),'switch_count':switch,'trajectory_type':'MULTISWITCH' if switch>1 else 'SIMPLE','terminal_action':seq[-1],'native_used_layer_union':used,'P0_materialized_layers':LAYERS,'P1_materialized_layers':used,'native_dynamic_score':r['native_dynamic_score'],'native_prediction_sha256':r['native_prediction_sha256'],'dynamic_result_path':r['dynamic_result_path'],'dynamic_result_sha256':r['dynamic_result_sha256'],'historical_overlap':False,'model_identity':MODEL,'checkpoint_identity':CKPT,'benchmark_identity':BENCH,'rule_hash':RULE,'eligibility_hash':ELIG,'amendment_hash':amend_sha})
 counts=Counter(x['trajectory_type'] for x in cohort)
 if len(cohort)!=167 or counts!=Counter({'SIMPLE':96,'MULTISWITCH':71}):raise RuntimeError('COHORT_COUNT '+repr(counts))
 cp=RUN/'manifests/KP_167_COHORT.jsonl';jsonl(cp,cohort);csha=sha(cp)
 manifest=[]
 for x in cohort:
  for cell,(k,p) in CELLS.items():
   q={'canonical_sample_id':x['canonical_sample_id'],'task':x['task'],'benchmark_global_index':x['benchmark_global_index'],'cell':cell,'K_bit':k,'P_bit':p,'boundary':x['boundary'],'prefix_chunks':x['prefix_chunks'],'continuation_chunks':x['continuation_chunks'],'full_native_dynamic_sequence':x['full_native_dynamic_sequence'],'control_prefix_sequence':x['control_prefix_sequence'],'frozen_terminal_suffix':x['frozen_terminal_suffix'],'native_used_layer_union':x['native_used_layer_union'],'P0_materialized_layers':LAYERS,'P1_materialized_layers':x['native_used_layer_union'],'model_identity':MODEL,'checkpoint_identity':CKPT,'benchmark_identity':BENCH,'rule_hash':RULE,'eligibility_hash':ELIG,'amendment_hash':amend_sha,'cohort_hash':csha,'branch_order':len(manifest)+1};q['branch_id']=canon(q);manifest.append(q)
 mp=RUN/'manifests/KP_668_BRANCH_MANIFEST.jsonl';jsonl(mp,manifest);msha=sha(mp)
 if len(manifest)!=668 or len({x['branch_id'] for x in manifest})!=668 or Counter(x['cell'] for x in manifest)!=Counter({c:167 for c in CELLS}):raise RuntimeError('MANIFEST_INVARIANT')
 protocol={'version':'KP_FACTORIAL_1P7B_FORMAL_V1','frozen_before_formal_factorial_outcomes':True,'model_identity':MODEL,'checkpoint_identity':CKPT,'benchmark_identity':BENCH,'rule_sha256':RULE,'eligibility_sha256':ELIG,'amendment_sha256':amend_sha,'cohort_sha256':csha,'branch_manifest_sha256':msha,'factor_order':'FIRST_BIT_K_SECOND_BIT_P','cells':{'F00':'Native fast weights + Control K + P0','F10':'Native fast weights + Native K + P0','F01':'Native fast weights + Control K + P1','F11':'Native fast weights + Native K + P1'},'K':'PREFIX_ATTENTION_KV_CONTEXT_ALL_ATTENTION_LAYERS_PREBOUNDARY','P':'TTT_CACHE_OCCUPANCY_AND_UNUSED_LAYER_FORWARD_PATH_IMPLEMENTATION_QUALIFIED','fast_weight_parity':'PER_LAYER_CONTIGUOUS_UINT16_RAW_BYTES_SHA256_TOLERANCE_0','primary_endpoint':'HISTORICAL_GENERATION_START_LOGIT_RELATIVE_L2_TO_NATIVE','effects':{'K_AT_P0':'d00-d10','K_AT_P1':'d01-d11','P_AT_K0':'d00-d01','P_AT_K1':'d10-d11','MAIN_K':'mean(K_AT_P0,K_AT_P1)_PER_SAMPLE','MAIN_P':'mean(P_AT_K0,P_AT_K1)_PER_SAMPLE','INTERACTION':'d00-d10-d01+d11'},'closure':{'L1':'all recorded first-continuation and first-post-boundary-update tensors torch.equal','L2':'all complete-continuation final-hidden chunks torch.equal','L3':'all incomplete-tail tensors torch.equal','L4':'generation-start logits torch.equal','L5':'decoded prediction SHA256 equal','L6':'L1 AND L2 AND L3 AND L4 AND L5','tolerance':0},'terminal_reward_role':'SECONDARY','branch_order':'SAMPLE_MAJOR_F00_F10_F01_F11','workers':1,'cpu_affinity':'8-23','bootstrap':{'role':'SECONDARY_FORMAL_UNCERTAINTY_ANALYSIS','paired_seed':20260827,'replicates':20000},'F11_integrity_target':167,'expected_branches':668,'R2_LAUNCHED':False,'CRITICALITY_LAUNCHED':False,'OBSERVABILITY_LAUNCHED':False,'created_at':now()}
 atomic(RUN/'preregistration/KP_FACTORIAL_1P7B_FORMAL_V1.json',protocol)
 atomic_text(RUN/'preregistration/KP_FACTORIAL_1P7B_FORMAL_V1.md','# Qwen3-1.7B Formal K/P 2x2 Factorial V1\n\nThis preregistration freezes all 167 independent eligible anchors and 668 sample-major branches before outcomes. K, P, exact fast-weight hash parity, historical generation-start relative-L2, sample-first contrasts, strict L1-L6 closure, secondary terminal reward, single-worker execution and the F11=167 integrity target are defined by the adjacent JSON protocol. No R2, criticality, observability, or Dynamic rerun is authorized.\n')
 psha=sha(RUN/'preregistration/KP_FACTORIAL_1P7B_FORMAL_V1.json')
 hist=Path('/home/USER/ttt_mechanism_analysis_v1/trajectory_closure_factorial_intervention_v1/scripts');closure=Path('/home/USER/ttt_mechanism_analysis_v1/trajectory_state_closure_audit_v1/scripts/closure_core.py')
 audit={'status':'PROVEN_EXACT','files':{str(p):sha(p) for p in [hist/'setup_authority.py',hist/'run_full_structural.py',hist/'factorial_core.py',closure,hist/'analyze_finalize.py']},'recovered_semantics':{'K':'PrefixKVInjectCache exact all-layer prefix K/V copy','P0':'inject/materialize all five candidate layers','P1':'inject/materialize Native used-layer union; absent candidates use ordinary MLP path','fast_hash':'contiguous uint16 raw-byte SHA256','tracer':'historical Recorder tensor selection and torch.equal','effects':'historical sample-first sign convention'},'formal_generalization':'Only schedule/boundary/used-union generalized by frozen pre-outcome amendment; low-level executor unchanged','timestamp':now()}
 atomic(RUN/'audit/HISTORICAL_KP_EXECUTOR_PARITY_AUDIT.json',audit)
 atomic_text(RUN/'audit/HISTORICAL_KP_EXECUTOR_PARITY_AUDIT.md','# Historical K/P Executor Parity Audit\n\nStatus: **PROVEN_EXACT**. The formal worker imports the immutable historical `factorial_core.py` and `closure_core.py` for K/V copying, fast-weight injection, P materialization/path semantics, tensor hashing and branch execution. The historical Recorder selection and analyzer formulas were recovered from the executed source. Only the complete-sequence, terminal-run boundary, OFF-prefix and full-sequence union amendment is new and was frozen before outcomes.\n')
 simple=next(x for x in cohort if x['trajectory_type']=='SIMPLE' and x['native_used_layer_union']!=LAYERS and any(a!='OFF' for a in x['full_native_dynamic_sequence'][:x['prefix_chunks']]))
 chosen=[];seen=set()
 for x in [q for q in cohort if q['trajectory_type']=='MULTISWITCH' and q['native_used_layer_union']!=LAYERS]:
  key=(tuple(x['native_used_layer_union']),x['boundary'])
  if key not in seen:chosen.append(x);seen.add(key)
  if len(chosen)==3:break
 if len(chosen)!=3:raise RuntimeError('SMOKE_DIVERSITY')
 smoke_orders=[simple['cohort_order']]+[x['cohort_order'] for x in chosen]
 config={'version':'KP_FACTORIAL_1P7B_FORMAL_V1','run_root':str(RUN),'python':'/home/USER/conda_envs/ttt_phase_c_v1/bin/python','model_root':'/home/USER/ttt/models/qwen3_1p7b_stage2','model_identity':MODEL,'checkpoint_identity':CKPT,'benchmark_root':'/home/USER/ttt/benchmarks/ruler_16k_standard_13task500_v1','benchmark_identity':BENCH,'dynamic_root':'/home/USER/ttt/runs/formal/dynamic_nonceiling_12task_1p7b_v1/run_20260828T161330+0800','dynamic_final_audit':str(dyn),'dynamic_final_audit_sha256':DYN,'screening_root':str(SCREEN),'rule_manifest':str(rule),'rule_sha256':RULE,'eligibility_manifest':str(elig),'eligibility_sha256':ELIG,'amendment':str(RUN/'preregistration/KP_FORMAL_AMENDMENT_V1.json'),'amendment_sha256':amend_sha,'cohort_manifest':str(cp),'cohort_sha256':csha,'branch_manifest':str(mp),'branch_manifest_sha256':msha,'protocol':str(RUN/'preregistration/KP_FACTORIAL_1P7B_FORMAL_V1.json'),'protocol_sha256':psha,'executor':'/home/USER/ttt_dynamic_mining_v1/phase_d_enriched_dynamic_mining_v1/runtime/code/dynamic_runner.py','scorer':'/home/USER/ttt/code/ruler/tools/common.py','historical_factorial_core':str(hist/'factorial_core.py'),'historical_factorial_core_sha256':sha(hist/'factorial_core.py'),'historical_closure_core':str(closure),'historical_closure_core_sha256':sha(closure),'worker':str(RUN/'scripts/kp_worker.py'),'worker_sha256':sha(RUN/'scripts/kp_worker.py'),'aggregator':str(RUN/'scripts/aggregate_kp.py'),'aggregator_sha256':sha(RUN/'scripts/aggregate_kp.py'),'controller':str(RUN/'scripts/run_kp_controller.sh'),'controller_sha256':sha(RUN/'scripts/run_kp_controller.sh'),'monitor':'/home/USER/ttt/scripts/monitor_kp_factorial_1p7b_v1.py','launcher':'/home/USER/ttt/scripts/run_kp_factorial_1p7b_v1.sh','tmux':'/home/USER/ttt_dynamic_mining_v1/phase_d_enriched_dynamic_mining_v1/runtime/tools/tmux','tmux_session':'kp_factorial_1p7b_v1','workers':1,'cpu_affinity':'8-23','expected_results':668,'smoke_orders':smoke_orders,'smoke_sample_ids':[simple['canonical_sample_id']]+[x['canonical_sample_id'] for x in chosen],'simple_trajectory_n':counts['SIMPLE'],'multiswitch_trajectory_n':counts['MULTISWITCH'],'paired_bootstrap_seed':20260827,'bootstrap_resamples':20000}
 atomic(RUN/'config/KP_FACTORIAL_FORMAL_CONFIG.json',config)
 pre={'status':'PASS','authority_checks':checks,'execution_cohort_n':167,'branch_manifest_n':668,'simple_n':counts['SIMPLE'],'multiswitch_n':counts['MULTISWITCH'],'historical_overlap':0,'kp_outcome_leakage':0,'transplant_v1_status':'WITHDRAWN_CAUSALLY_CONFOUNDED','cohort_frozen':True,'formal_outcomes_seen':False,'smoke_orders':smoke_orders,'hashes':{'amendment':amend_sha,'cohort':csha,'branch_manifest':msha,'protocol':psha},'timestamp':now()}
 atomic(RUN/'audit/PRELAUNCH_AUTHORITY_AND_FREEZE_AUDIT.json',pre);atomic(RUN/'status/pipeline_status.json',{'pipeline_status':'SETUP_FROZEN','current_phase':'READY_FOR_SMOKE','cohort_n':167,'total_expected':668,'committed_results':0,'smoke_status':'PENDING','formal_launched':False,'updated_at':now()})
 print(json.dumps(pre,sort_keys=True))
if __name__=='__main__':main()
