"""CPU-only synthetic state tests; never invokes a trainer or publishes FINAL."""
import copy,json,os,subprocess,sys,time,types,uuid
from pathlib import Path
from unittest.mock import patch
import pipeline_core as core
import pipeline_supervisor as sup
from pipeline_finalize import stage1_parent_fields
R=core.ROOT;c=core.config();A=R/'audits/qwen3_4b_stage1_stage2_pipeline_formal_v1';T=R/'work/qwen3_4b_stage1_stage2_pipeline_formal_v1/tests'/str(time.time_ns());T.mkdir(parents=True)
results=[]
sup.SOURCE=T/'SOURCE_AUTHORITY_TEST_FIXTURE.json';core.atomic(sup.SOURCE,{'TEST_FIXTURE':True,'NO_REAL_AUTHORITY':True})
def case(name,fn,reject=False):
 try:fn()
 except (RuntimeError,KeyError,FileNotFoundError,ValueError) as e:
  if not reject:raise
  results.append({'test':name,'status':'PASS','rejected':True,'reason':str(e)});return
 if reject:raise AssertionError('ACCEPTED_INVALID '+name)
 results.append({'test':name,'status':'PASS'})
guard=core.module(c['stage1']['guard'],'test_actual_v41_guard');auth=core.read(c['stage1']['authority'])
case('actual_V4_1_authority_accepted',lambda:guard.validate_v4_1_authority(auth))
for version in ['V1','V2','V3','V4']:
 bad=copy.deepcopy(auth);bad['PRELAUNCH_AUTHORITY_VERSION']=version;case('reject_'+version+'_instead_of_V4_1',lambda bad=bad:guard.validate_v4_1_authority(bad),True)
bad=copy.deepcopy(auth);bad['SAFE_TO_LAUNCH_QWEN3_4B_STAGE1_1B_32K_GPU23']='NO';case('invalid_stage1_authority',lambda:guard.validate_v4_1_authority(bad),True)
case('bad_stage1_config_hash',lambda:core.check_hashes({c['stage1']['config']:'0'*64}),True)
case('bad_stage2_dataset_hash',lambda:core.check_hashes({str(R/'shared/datasets/authority/STAGE2_DATASET_AUTHORITY.json'):'0'*64}),True)
# Run the exact formal Stage2 parser against in-memory schemas generated by
# the production Stage1 field builder. No real FINAL authority is fabricated.
parser=core.module(c['stage2']['controller'],'test_exact_stage2_parser');fake=T/'IN_MEMORY_SCHEMA_ONLY';ap=fake/'STAGE1_FINAL_AUTHORITY.json'
meta={'model_identity':'Qwen3-4B','ttt_layers':[0,6,12,18,24,30],'context_length':32768,'record_cursor':38335,'cumulative_tokens':989996971,'config_sha256':core.digest(c['stage1']['config']),'tokenizer_sha256':core.digest(Path(c['base_model'])/'tokenizer.json'),'PARENT_CLASS':'STAGE1_FINAL','DEBUG_ONLY':False}
generated=stage1_parent_fields(meta,fake,'weight-hash','manifest-hash');manifest={'format':'gated_ntp_stage1_model_only_dcp_v1','complete':True,'metadata':meta,'files':{'model.pt':'weight-hash'}}
def exact_parser_test(a,m):
 def load(path):return a if Path(path)==ap else m
 def sha(path):
  if Path(path)==fake/'manifest.json':return 'manifest-hash'
  if Path(path)==fake/'model.pt':return 'weight-hash'
  return core.digest(path)
 with patch.object(parser,'load',load),patch.object(parser,'sha',sha):return parser.parent_contract(ap)
case('generated_stage1_schema_exact_stage2_parent_parser',lambda:exact_parser_test(generated,manifest))
for field,value in [('DEBUG_ONLY',True),('PARENT_CLASS','DEBUG_ONLY'),('stage1_completed',False),('record_cursor',38334),('cumulative_tokens',989996970),('checkpoint_sha256','wrong')]:
 bad={**generated,field:value};case('parent_reject_'+field,lambda bad=bad:exact_parser_test(bad,manifest),True)
case('actual_DEBUG_parent_rejected_formal',lambda:parser.parent_contract(core.read(c['stage2']['authority'])['DEBUG_STAGE1_PARENT_AUTHORITY']),True)
# Real completion implementation against explicit synthetic run receipts.
def make_run(stage):
 run=T/f'stage{stage}_synthetic';run.mkdir();e=c[f'stage{stage}']['expected'];cfgpath=Path(c[f'stage{stage}']['config'])
 import yaml
 cfg=yaml.safe_load(cfgpath.read_text())
 if stage==2:(run/'resolved_config.yaml').write_bytes(cfgpath.read_bytes());cfgpath=run/'resolved_config.yaml'
 core.atomic(run/'TEST_FIXTURE.json',{'TEST_FIXTURE':True,'REAL_TRAINING':False})
 core.atomic(run/'complete.json',{'complete':True,'stage':stage,'record_cursor':e['record_cursor'],'cumulative_tokens':e['cumulative_tokens']})
 (run/'training.jsonl').write_text(json.dumps({**e,'rank_runtime':[{'weights_finite':True},{'weights_finite':True}]})+'\n')
 (run/'launcher.log').write_text('FINAL_BARRIER_PASS\nRANK_0_SHUTDOWN_PASS\nRANK_1_SHUTDOWN_PASS\n')
 core.atomic(run/'launcher_exit.json',{'exit_code':0,'complete_verified':True})
 slot=run/'checkpoints/slot_A';slot.mkdir(parents=True);(slot/'fixture_payload').write_bytes(b'CPU_SYNTHETIC_NOT_A_DCP')
 m={'complete':True,'progress':{**e,'stage':stage,'input_identity':{**cfg['input_identity'],'config_sha256':core.digest(cfgpath)}},'files':{'fixture_payload':core.digest(slot/'fixture_payload')}}
 core.atomic(slot/'manifest.json',m);core.atomic(run/'checkpoints/latest.json',{'slot':'slot_A','manifest_sha256':core.digest(slot/'manifest.json')});return run
for stage in (1,2):
 run=make_run(stage);case(f'stage{stage}_exact_completion_contract',lambda stage=stage,run=run:core.completion(run,stage,c))
 original=core.read(run/'complete.json')
 for field,val in [('complete',False),('record_cursor',-1),('cumulative_tokens',-1)]:
  core.atomic(run/'complete.json',{**original,field:val});case(f'stage{stage}_reject_{field}',lambda stage=stage,run=run:core.completion(run,stage,c),True)
 core.atomic(run/'complete.json',original)
 originalrow=(run/'training.jsonl').read_text();row=json.loads(originalrow);(run/'training.jsonl').write_text(json.dumps({**row,'update_step':-1})+'\n');case(f'stage{stage}_reject_wrong_update_step',lambda stage=stage,run=run:core.completion(run,stage,c),True);(run/'training.jsonl').write_text(originalrow)
 if stage==2:
  for field in ['cumulative_answer_positions','cumulative_context_positions']:
   (run/'training.jsonl').write_text(json.dumps({**row,field:-1})+'\n');case('stage2_reject_'+field,lambda:core.completion(run,2,c),True)
  (run/'training.jsonl').write_text(originalrow)
for stage in (1,2):
 collision=T/f'bad_final{stage}';collision.mkdir();case(f'reject_mismatched_existing_FINAL_{stage}',lambda stage=stage,collision=collision:core.validate_final(collision,stage,c),True)
# Lock is exercised by a distinct CPU process, not a mocked flock.
with core.lock(T/'exclusive.lock'):
 command=[sys.executable,'-c','import fcntl,sys;f=open(sys.argv[1],"a");fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB)',str(T/'exclusive.lock')]
 result=subprocess.run(command,capture_output=True);assert result.returncode!=0;results.append({'test':'two_simultaneous_supervisors_rejected','status':'PASS'})
state={'state':'PRECHECK','history':[]}
for next_state in core.STATES[1:]:state=core.transition(state,next_state,'hash',T,'synthetic state transition')
assert len(state['history'])==9;results.append({'test':'full_state_machine_sequence','status':'PASS'})
case('reject_state_regression',lambda:core.transition(state,'STAGE1_RUNNING','hash',T,'bad'),True)
# Production launch journals with mocked Popen only. No launcher subprocess.
for stage in (1,2):
 cc=copy.deepcopy(c);cc['state_root']=str(T/f'journal{stage}');cc['stage1']['final_root']=str(T/'absent_final1');cc['stage2']['final_root']=str(T/'absent_final2')
 snap={'run_root':None,'status':'NOT_STARTED'};fakeproc=types.SimpleNamespace(pid=os.getpid(),wait=lambda:0)
 with core.lock(Path(cc['state_root'])/'PIPELINE.lock') as fd:
  supervisor=sup.Supervisor(cc,fd)
  with patch.object(sup,'stage_snapshot',side_effect=[snap,{'run_root':str(T/f'job{stage}') }]),patch.object(sup,'validate_final',return_value={}),patch.object(sup.subprocess,'Popen',return_value=fakeproc) as pop:
   supervisor.launch(stage);assert pop.call_count==1
  case(f'duplicate_stage{stage}_launch_rejected',lambda:supervisor.launch(stage),True)
  journal=core.read(supervisor.journal_path(stage));assert sup.action_policy(stage,cc,journal,snap)=='BLOCK_UNCERTAIN_OR_FAILED_PRIOR_ATTEMPT'
  active={**snap,'process_identities':[{'pid':123,'start_ticks':42,'command':'synthetic'}]};assert sup.action_policy(stage,cc,journal,active)=='ADOPT_ACTIVE';results.append({'test':f'stage{stage}_restart_adopts_active_without_launch','status':'PASS'})
  # Simulate supervisor-only recovery through the real step function.
  with patch.object(sup,'stage_snapshot',return_value=active),patch.object(sup,'validate_final',return_value={}):
   supervisor.step();assert supervisor.state['state']=='STAGE1_RUNNING'
  results.append({'test':f'supervisor_recovery_no_Popen_{stage}','status':'PASS'})
 # Durable pre-spawn crash window must never authorize another trainer.
 assert sup.action_policy(stage,cc,{'phase':'INTENT'},snap)=='BLOCK_UNCERTAIN_OR_FAILED_PRIOR_ATTEMPT';results.append({'test':f'stage{stage}_intent_crash_window_fail_closed','status':'PASS'})
require=core.require
require(not any('torchrun' in str(x.get('command','')) for x in []),'NO_TRAINER_CALL')
report={'status':'PASS','created_at':time.time(),'tests':results,'test_count':len(results),'TEST_FIXTURE_ROOT':str(T),'formal_authorities_fabricated':False,'formal_training_started':False,'GPU_used':False,'exact_stage2_parser_used':True,'fixtures_scope':'Only CPU synthetic receipts / in-memory parent schema. Not actual completed formal artifacts.','source_sha256':core.digest(Path(__file__))}
core.atomic(A/'CPU_CONTRACT_TESTS.json',report);print(json.dumps(report,indent=2))
