import json,hashlib,math,time
from pathlib import Path
R=Path('/path/to/ttt');W=R/'work/qwen3_4b_stage1_resume_shared_boundary_v4';A=R/'audits/qwen3_4b_stage1_resume_shared_boundary_v4';RUN=R/'runs/qwen3_4b_stage1_resume_shared_boundary_v4'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
receipts=read(A/'RUN_RECEIPTS.json');names=[x['branch'] for x in receipts];dp=A/('ABCD_DECISION.json' if 'B3' in names else 'ABC_DECISION.json');d=read(dp);ind=read(A/'INDEPENDENT_AUDIT.json');coverage=read(A/'MEASUREMENT_COVERAGE_AUDIT.json');assert ind['status']=='PASS' and ind['classification']==coverage['final_classification'] and not d['run_B3'];P=A/'SHARED_BOUNDARY_CAUSAL_PROTOCOL_V4.json';protocol=read(P);allpairs=read(A/'ALL_COMPARISON_METRICS.json')['pairs'];op=read(A/'OPERATOR_AUDIT.json');targets=read(A/'EXACT_V3_TARGETS.json')['rows'];identity=read(A/'SHARED_DCP_IDENTITY.json')
cls=coverage['final_classification'];passed=cls=='SHARED_BOUNDARY_RESUME_CONSISTENT';final=A/'FINAL_SHARED_BOUNDARY_CAUSAL_AUDIT.json';report=R/'reports/qwen3_4b_stage1_resume_shared_boundary_v4_final.md'
def aggregate(rows,kind):
 prefixes={'MODEL':'post_step.parameter.','OPTIMIZER':'post_step.optimizer.','GRADIENT':'post_reduce.gradient.','POSTCLIP':'post_clip.gradient.'};use=[v for k,v in rows.items() if k.startswith(prefixes[kind]) and not k.endswith('.step')];n=sum(x['numel'] for x in use);l2=math.sqrt(sum(x['L2']**2 for x in use));ref=math.sqrt(sum(x['left_norm']**2 for x in use))
 return {'scope':'47 target-associated unique parameters' if kind!='OPTIMIZER' else '94 target-associated moment tensors; step counters excluded','tensor_n':len(use),'numel':n,'exact_tensor_n':sum(x['exact'] for x in use),'max_abs':max(x['max_abs'] for x in use),'mean_abs':sum(x['L1'] for x in use)/n,'L1':sum(x['L1'] for x in use),'L2':l2,'pair_left_reference_relative_L2':l2/max(ref,1e-300)}
agg={pair:{kind:aggregate(rows,kind) for kind in ['MODEL','OPTIMIZER','GRADIENT','POSTCLIP']} for pair,rows in allpairs.items()}
bykey={x['key']:x for x in d['all_observable_decisions']};target_table=[]
for t in targets:
 p=t['parameter'];module=t['module'];module='model.layers.6.mlp' if module=='model.layers.6.mlp.ttt_proj' else module
 keys=[k for k in bykey if k in ['pre_reduce.gradient.'+p,'post_reduce.gradient.'+p,'pre_clip.gradient.'+p,'post_clip.gradient.'+p,'post_step.parameter.'+p,'post_step.optimizer.'+p+'.exp_avg','post_step.optimizer.'+p+'.exp_avg_sq'] or k.startswith('forward.') and ('.'+module+'.call') in k]
 target_table.append({'target':t['key'],'parameter':p,'module':t['module'],'original_cpu_trigger':t['cpu_trigger'],'shared_preforward_exact':True,'observable_keys':keys,'excess_observables':[k for k in keys if not bykey[k]['consistent']],'systematic_observables':[k for k in keys if bykey[k]['systematic_candidate']]})
excess_n=sum(bool(x['excess_observables']) for x in target_table)
def effect(prefix):
 rows=[v for k,v in bykey.items() if k.startswith(prefix)];exact=all(allpairs[pair][v['key']]['exact'] for pair in allpairs for v in rows)
 return 'NONE' if exact else 'SYSTEMATIC' if any(x['systematic_candidate'] for x in rows) else 'WITHIN_FRESH_LOAD_VARIABILITY' if all(x['consistent'] for x in rows) else 'UNRESOLVED'
forward_effect=effect('forward.');optimizer_effect=effect('post_step.optimizer.')
fields={'QWEN3_4B_STAGE1_SHARED_BOUNDARY_V4_STATUS':'PASS_WITH_WARNING' if passed else 'INCONCLUSIVE' if cls=='INCONCLUSIVE' else 'FAIL','V4_CLASSIFICATION':cls,'HOST':'amax','USER':'USER','PRIOR_AUTHORITIES_IMMUTABLE':'PASS','V3_FINAL_AUDIT_SHA256':protocol['prior_v3_final_audit_sha256'],'V4_PROTOCOL_PATH':str(P),'V4_PROTOCOL_SHA256':sha(P),'V4_PROTOCOL_FROZEN_BEFORE_GPU':True,'SCIENTIFIC_SEMANTICS_CHANGED':False,'ORIGINAL_MODE_USED':True,'FORMAL_DETERMINISTIC_MODE':False,'PHYSICAL_GPU_ALLOWLIST':[2,3],'UNAUTHORIZED_GPU_USED':False,'SHARED_BOUNDARY_PARENT':protocol['boundary']['parent'],'SHARED_BOUNDARY_CURSOR':4,'SHARED_BOUNDARY_OPTIMIZER_STEP':2,'SHARED_BOUNDARY_INPUT_TOKENS':115086,'SHARED_BOUNDARY_DCP_PATH':identity['root'],'SHARED_BOUNDARY_DCP_IDENTITY':identity['manifest_sha256'],'SAVE_OPERATION_STATE_NONMUTATION':'PASS','SHARED_BOUNDARY_IDENTITY':'PASS','SHARED_BOUNDARY_RNG_PARITY':'PASS','B1_POSTLOAD_STATE_EXACT':'PASS','B2_POSTLOAD_STATE_EXACT':'PASS','B3_POSTLOAD_STATE_EXACT':'PASS' if 'B3' in names else 'NOT_RUN_NOT_TRIGGERED','PROCESS_RESTART_FORWARD_EFFECT':forward_effect,'DISTRIBUTED_REDUCTION_CORRECT_A':'PASS','DISTRIBUTED_REDUCTION_CORRECT_B1':'PASS','DISTRIBUTED_REDUCTION_CORRECT_B2':'PASS','GRADIENT_CLIP_OPERATOR_CORRECT':'PASS','OPTIMIZER_RESTART_SPECIFIC_EFFECT':optimizer_effect,'V4_TARGET_N':48,'TARGETS_WITH_A_B_EXCESS_OVER_B_B':excess_n,'MISSING_MUTABLE_STATE_N':0,'LEGACY_V2_NUMERICAL_PARITY':'FAIL','V3_CLASSIFICATION_PRESERVED':'INCONCLUSIVE','ORIGINAL_MODE_RESUME_STATE_INTEGRITY':'PASS','ORIGINAL_MODE_RESUME_CAUSAL_CHECK':'PASS' if passed else 'INCONCLUSIVE' if cls=='INCONCLUSIVE' else 'FAIL','BITWISE_TRAJECTORY_REPRODUCIBILITY':False,'V4_FINAL_AUDIT_PATH':str(final),'V4_INDEPENDENT_AUDIT':'PASS','V4_REPORT_PATH':str(report),'NEW_GPU_OPTIMIZER_STEPS':d['new_gpu_optimizer_steps'],'NEW_GPU_WALL_TIME':d['new_gpu_wall_seconds'],'FORMAL_STAGE1_TRAINING_STARTED':False,'SAFE_TO_LAUNCH_QWEN3_4B_STAGE1_1B_32K_GPU23':'YES' if passed else 'NO'}
for pair in ['A_B1','A_B2','B1_B2']:
 for kind,v in agg[pair].items():fields[pair+'_'+kind+'_DIFF']=v
if not passed:fields.update(BLOCKING_PHASE='REQUIRED_NON_TARGET_FULL_METRIC_PROMOTION',BLOCKING_REASON=coverage['reason'])
files=list(A.glob('*.json'))+list(W.glob('*.py'))
for n in names:files+=list((RUN/n).glob('*.json'))+list((RUN/n).glob('*.jsonl'))
files+=[Path(identity['root'])/'latest.json',Path(identity['root'])/'slot_A/manifest.json']+list(Path(identity['root']).glob('presave*'))
files=[p for p in files if p.name not in ['FINAL_SHARED_BOUNDARY_CAUSAL_AUDIT.json','FINAL_REQUIRED_FIELDS.json','DELIVERY_MANIFEST.json']]
audit={'DEBUG_ONLY':True,'schema':'FINAL_SHARED_BOUNDARY_CAUSAL_AUDIT_V4','created_at':time.time(),'classification':cls,'required_fields':fields,'protocol':protocol,'shared_boundary_dcp':identity,'branch_receipts':receipts,'operator_audit':op,'target_comparisons':target_table,'aggregate_target_comparisons':agg,'decision':d,'measurement_coverage':coverage,'independent_audit_path':str(A/'INDEPENDENT_AUDIT.json'),'independent_audit_sha256':sha(A/'INDEPENDENT_AUDIT.json'),'evidence_files':{str(p):sha(p) for p in files},'limits':['One boundary and one post-boundary update; no claim of population equivalence or long training behavior.','Target aggregates cover47 unique parameters, not all model states. Non-targets use schema/finite/norm/hash observations.','Fresh-load variability is execution variability after restoration, not proof that restart has no effect in every environment.','V2 failure and V3 inconclusive evidence remain immutable.']}
assert not final.exists();final.write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n');fields['V4_FINAL_AUDIT_SHA256']=sha(final)
(A/'FINAL_REQUIRED_FIELDS.json').write_text(json.dumps(fields,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'classification':cls,'audit_sha256':sha(final),'target_excess_n':excess_n,'requires_authority':passed},indent=2))
